baseURL = 'https://keruenn.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"
